apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-qa          # ← overrides ALL resource namespaces

namePrefix: qa-                   # optional: prefixes resource names

resources:
  - ../../base
  - namespace.yaml                 # env-specific namespace

patches:
  - path: patch-prometheus-config.yaml   # ← must be an object with "path:" key
  - path: patch-resources.yaml
  - path: prometheus-rbac-patch.yaml
  - path: patch-grafana-datasource.yaml
  - path: patch-grafana-service.yaml


labels:
  - pairs:
      environment: qa