# overlays/dev/patch-prometheus-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s          # slower scrape in dev is fine

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: blog-backend
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [dwp-dev]           # ← scoped to this env's app namespace

      - job_name: blackbox-dwp-platform-ui
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              # ← env-specific service DNS
              - http://dwp-platform-ui.dwp-dev.svc.cluster.local/health
              - http://dwp-platform-ui.dwp-dev.svc.cluster.local/
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter.monitoring-dev.svc.cluster.local:9115